### ISSUE TITLE
Tail -f example does not work with mate editor on OSX

### ISSUE THREAD

**Issue by sammy007** [dullgiulio/ringio#2]
ringio logs open &
ringio logs input tail -f text.txt
ringio logs output

echo 1 >> text.txt
Works fine, text printed to console, but if text.txt altered with textmate it does not work and completely breaks output.

**Comment by dullgiulio** [comment]
What do you mean exactly with "completely breaks output"?

It is possible that TextMate writes the file atomically (i.e. replaces the file) and tail doesn't notice this?

Can you paste the complete output? Thanks!
